# Generated by Django 5.2.3 on 2025-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок блога",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите текст", null=True, verbose_name="Содержимое"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Blogs/preview/",
                        verbose_name="Превью блога",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовано?",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "views_counter",
                    models.IntegerField(
                        default=0,
                        help_text="Количество просмотров блога",
                        verbose_name="Просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["created_at"],
            },
        ),
    ]
